import type { Ingredient } from "./types";

export const ingredients: Ingredient[] = [
{"slug": "oats", "name": "Rolled oats", "description": "Whole-grain oats with soluble fiber and slow-digesting carbohydrate.", "image": "https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 389, "protein": 16.9, "carbs": 66.3, "fat": 6.9, "fiber": 10.6}, "category": "Grain", "notes": "Dry oats are calorie dense; weighing the dry portion is the clearest way to track them."},
{"slug": "greek-yogurt", "name": "Greek yogurt", "description": "Thick cultured dairy with a high protein-to-calorie ratio.", "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 97, "protein": 9.0, "carbs": 3.9, "fat": 5.0, "fiber": 0}, "category": "Dairy", "notes": "Nutrition varies by fat percentage and brand. Use the package label when available."},
{"slug": "berries", "name": "Mixed berries", "description": "Fresh berries provide vitamin C, polyphenols and fiber with relatively low energy density.", "image": "https://images.unsplash.com/photo-1425934398893-310a009a77f9?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 50, "protein": 0.8, "carbs": 12.0, "fat": 0.4, "fiber": 4.0}, "category": "Fruit", "notes": "Frozen unsweetened berries are nutritionally comparable to fresh for most purposes."},
{"slug": "chia", "name": "Chia seeds", "description": "Tiny seeds rich in fiber, alpha-linolenic acid and minerals.", "image": "https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 486, "protein": 16.5, "carbs": 42.1, "fat": 30.7, "fiber": 34.4}, "category": "Seed", "notes": "Small portions add up quickly because seeds are energy dense."},
{"slug": "almond-butter", "name": "Almond butter", "description": "Ground almonds providing mostly unsaturated fat plus protein and fiber.", "image": "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 603, "protein": 20.8, "carbs": 21.2, "fat": 53.0, "fiber": 9.7}, "category": "Nut butter", "notes": "Use the product label for a packaged jar because added sugar or oil can change values."},
{"slug": "quinoa", "name": "Cooked quinoa", "description": "A cooked pseudo-grain containing carbohydrate, fiber and modest protein.", "image": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 120, "protein": 4.4, "carbs": 21.3, "fat": 1.9, "fiber": 2.8}, "category": "Grain", "notes": "These values are for cooked quinoa, not dry quinoa."},
{"slug": "tofu", "name": "Firm tofu", "description": "Soy-based protein food with calcium and iron depending on how it is set.", "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 144, "protein": 17.3, "carbs": 2.8, "fat": 8.7, "fiber": 2.3}, "category": "Protein", "notes": "Firmness and calcium content vary by brand, so packaged tofu labels are useful."},
{"slug": "edamame", "name": "Cooked edamame", "description": "Young soybeans with protein, fiber and carbohydrate.", "image": "https://images.unsplash.com/photo-1563897539633-7374c276c212?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 121, "protein": 11.9, "carbs": 8.9, "fat": 5.2, "fiber": 5.2}, "category": "Legume", "notes": "Track shelled edible weight rather than pod weight."},
{"slug": "tahini", "name": "Tahini", "description": "Sesame seed paste rich in unsaturated fat and minerals.", "image": "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 595, "protein": 17.0, "carbs": 21.2, "fat": 53.8, "fiber": 9.3}, "category": "Seed butter", "notes": "Like nut butter, tahini is very energy dense; tablespoon-sized differences matter."},
{"slug": "lentils", "name": "Cooked lentils", "description": "High-fiber legume with plant protein, folate and iron.", "image": "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 116, "protein": 9.0, "carbs": 20.1, "fat": 0.4, "fiber": 7.9}, "category": "Legume", "notes": "These numbers are for cooked lentils."},
{"slug": "rice", "name": "Cooked brown rice", "description": "Cooked whole-grain rice providing carbohydrate, manganese and some fiber.", "image": "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 123, "protein": 2.7, "carbs": 25.6, "fat": 1.0, "fiber": 1.6}, "category": "Grain", "notes": "Cooked weight is much heavier than dry weight because of absorbed water."},
{"slug": "spinach", "name": "Spinach", "description": "Leafy green vegetable rich in folate, carotenoids and vitamin K.", "image": "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 23, "protein": 2.9, "carbs": 3.6, "fat": 0.4, "fiber": 2.2}, "category": "Vegetable", "notes": "Cooked spinach is more compact, so grams can look very different from raw volume."},
{"slug": "chickpeas", "name": "Cooked chickpeas", "description": "Fiber-rich legume with carbohydrate and plant protein.", "image": "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 164, "protein": 8.9, "carbs": 27.4, "fat": 2.6, "fiber": 7.6}, "category": "Legume", "notes": "Canned chickpeas can be tracked after draining and rinsing."},
{"slug": "tomato", "name": "Tomato", "description": "Water-rich vegetable/fruit with vitamin C and carotenoids.", "image": "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 18, "protein": 0.9, "carbs": 3.9, "fat": 0.2, "fiber": 1.2}, "category": "Vegetable", "notes": "Fresh tomatoes are very low in energy density."},
{"slug": "cucumber", "name": "Cucumber", "description": "Hydrating, low-energy vegetable often used in bowls and salads.", "image": "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 15, "protein": 0.7, "carbs": 3.6, "fat": 0.1, "fiber": 0.5}, "category": "Vegetable", "notes": "Peel and seed choices change texture more than calories."},
{"slug": "avocado", "name": "Avocado", "description": "Fruit rich in monounsaturated fat, potassium and fiber.", "image": "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 160, "protein": 2.0, "carbs": 8.5, "fat": 14.7, "fiber": 6.7}, "category": "Fruit", "notes": "Because avocado is energy dense, weighing the edible portion improves accuracy."},
{"slug": "egg", "name": "Whole egg", "description": "Complete protein with fat-soluble vitamins and choline.", "image": "https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 143, "protein": 12.6, "carbs": 0.7, "fat": 9.5, "fiber": 0}, "category": "Protein", "notes": "One large egg is usually around 50 g edible weight."},
{"slug": "black-beans", "name": "Cooked black beans", "description": "Fiber-rich legume with carbohydrate, protein, magnesium and folate.", "image": "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 132, "protein": 8.9, "carbs": 23.7, "fat": 0.5, "fiber": 8.7}, "category": "Legume", "notes": "Use drained weight for canned beans."},
{"slug": "whole-wheat-wrap", "name": "Whole-wheat tortilla", "description": "Flatbread providing carbohydrate and some fiber.", "image": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 310, "protein": 9.0, "carbs": 52.0, "fat": 8.0, "fiber": 6.0}, "category": "Grain", "notes": "Packaged wraps vary substantially, so the label is preferred."},
{"slug": "paneer", "name": "Paneer", "description": "Fresh cheese providing protein, calcium and fat.", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 265, "protein": 18.0, "carbs": 3.0, "fat": 20.0, "fiber": 0}, "category": "Dairy", "notes": "Fat level varies by recipe and brand."},
{"slug": "tempeh", "name": "Tempeh", "description": "Fermented soy food with protein, fiber and a firm texture.", "image": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 195, "protein": 19.9, "carbs": 7.6, "fat": 11.4, "fiber": 3.9}, "category": "Protein", "notes": "Tempeh absorbs sauces; track added oil or sugary marinades separately."},
{"slug": "kidney-beans", "name": "Cooked kidney beans", "description": "Legume rich in fiber, carbohydrate and plant protein.", "image": "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 127, "protein": 8.7, "carbs": 22.8, "fat": 0.5, "fiber": 6.4}, "category": "Legume", "notes": "Kidney beans should be fully cooked before eating."},
{"slug": "bell-pepper", "name": "Bell pepper", "description": "Crunchy vegetable rich in vitamin C and carotenoids.", "image": "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 31, "protein": 1.0, "carbs": 6.0, "fat": 0.3, "fiber": 2.1}, "category": "Vegetable", "notes": "Color changes micronutrient profile slightly but calories stay low."},
{"slug": "red-lentil-pasta", "name": "Cooked red lentil pasta", "description": "Legume-based pasta with more protein and fiber than many wheat pastas.", "image": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 160, "protein": 10.0, "carbs": 28.0, "fat": 2.0, "fiber": 4.0}, "category": "Grain/legume", "notes": "Check package data because brands vary."},
{"slug": "banana", "name": "Banana", "description": "Fruit providing carbohydrate, potassium and vitamin B6.", "image": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 89, "protein": 1.1, "carbs": 22.8, "fat": 0.3, "fiber": 2.6}, "category": "Fruit", "notes": "Weigh peeled edible fruit for the most precise gram tracking."},
{"slug": "peanut-butter", "name": "Peanut butter", "description": "Ground peanuts providing unsaturated fat, protein and some fiber.", "image": "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 588, "protein": 25.1, "carbs": 20.0, "fat": 50.4, "fiber": 6.0}, "category": "Nut butter", "notes": "Package labels differ if sugar or oil is added."},
{"slug": "falafel", "name": "Falafel", "description": "Chickpea-based patties with herbs and spices; energy depends heavily on cooking method.", "image": "https://images.unsplash.com/photo-1593001874117-c99c800e3eb3?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 333, "protein": 13.3, "carbs": 31.8, "fat": 17.8, "fiber": 4.9}, "category": "Prepared food", "notes": "Baked and fried falafel can differ considerably in calories."},
{"slug": "potato", "name": "Boiled potato", "description": "Starchy vegetable providing carbohydrate, potassium and vitamin C.", "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 87, "protein": 1.9, "carbs": 20.1, "fat": 0.1, "fiber": 1.8}, "category": "Vegetable", "notes": "Added oil or butter matters much more than the potato itself."},
{"slug": "broccoli", "name": "Broccoli", "description": "Cruciferous vegetable with vitamin C, folate and fiber.", "image": "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 35, "protein": 2.4, "carbs": 7.2, "fat": 0.4, "fiber": 3.3}, "category": "Vegetable", "notes": "Raw and cooked weights differ because of water."},
{"slug": "soy-milk", "name": "Unsweetened soy milk", "description": "Plant milk with protein and often added calcium and vitamin D.", "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 33, "protein": 2.9, "carbs": 1.7, "fat": 1.6, "fiber": 0.6}, "category": "Beverage", "notes": "Use the carton label because fortification and sweetening vary."},
{"slug": "plant-protein", "name": "Plant protein powder", "description": "Concentrated protein powder usually made from pea, soy, rice or blends.", "image": "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=1000&q=85", "per100": {"calories": 380, "protein": 75.0, "carbs": 10.0, "fat": 5.0, "fiber": 5.0}, "category": "Supplemental food", "notes": "Use your product label; powders vary a lot."},
];

export const ingredientBySlug = Object.fromEntries(ingredients.map(i => [i.slug, i])) as Record<string, Ingredient>;

