import type { WorkoutDay } from "./types";

export const workouts: WorkoutDay[] = [
{"day": 1, "week": 1, "type": "Strength circuit", "name": "Lower Body Foundations", "minutes": 28, "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=85", "summary": "Two 7-minute circuits, repeated once. Move steadily and prioritize form.", "instructions": ["Warm up for 5 minutes.", "Circuit A: squat 15, reverse lunge 10/side, glute bridge 15, calf raise 20.", "Rest 60 seconds.", "Circuit B: step-up 12/side, squat pulse 12, single-leg bridge 10/side, wall sit 30 sec.", "Repeat Circuit A and Circuit B once."]},
{"day": 2, "week": 1, "type": "Cardio + core", "name": "Brisk Cardio & Core", "minutes": 40, "image": "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=85", "summary": "Conversational cardio followed by a controlled core block.", "instructions": ["5-minute easy warm-up.", "30 minutes brisk walk, bike or elliptical.", "2\u20133 rounds: dead bug 10/side, bird dog 10/side, side plank 20\u201330 sec/side.", "5-minute cool-down."]},
{"day": 3, "week": 1, "type": "Strength circuit", "name": "Upper Body & Core", "minutes": 28, "image": "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=85", "summary": "Use dumbbells, a band, or a loaded backpack for resistance.", "instructions": ["Warm up shoulders and upper back for 5 minutes.", "Circuit A: incline push-up 10\u201312, bent-over row 12, shoulder tap 10/side, dead bug 10/side.", "Circuit B: overhead press 10\u201312, row 12, elevated plank 30 sec, side plank 20 sec/side.", "Repeat both circuits once."]},
{"day": 4, "week": 1, "type": "Recovery", "name": "Mobility & Easy Walk", "minutes": 25, "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=85", "summary": "Keep this easy enough that you finish feeling better than you started.", "instructions": ["15\u201320 minute easy walk.", "Hip flexor stretch 45 sec/side.", "90/90 hip switches 8/side.", "Thoracic rotation 8/side.", "Calf stretch 45 sec/side.", "2 minutes slow breathing."]},
{"day": 5, "week": 1, "type": "Conditioning", "name": "Full Body Conditioning", "minutes": 28, "image": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1200&q=85", "summary": "Low-impact options are fine. Keep one or two reps in reserve.", "instructions": ["Circuit A: squat to press 12, reverse lunge + knee drive 8/side, high-plank step-out 10/side, backpack deadlift 12.", "Circuit B: step-up 10/side, incline push-up 10, slow mountain climber 12/side, bridge march 12/side.", "Repeat both circuits once."]},
{"day": 6, "week": 1, "type": "Cardio", "name": "Steady Cardio", "minutes": 40, "image": "https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=85", "summary": "Choose walking, cycling, swimming or elliptical at a steady sustainable pace.", "instructions": ["5-minute easy warm-up.", "30 minutes steady cardio at RPE 5\u20136.", "5-minute cool-down.", "Optional 5-minute mobility."]},
{"day": 7, "week": 1, "type": "Rest", "name": "Rest & Reset", "minutes": 15, "image": "https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?auto=format&fit=crop&w=1200&q=85", "summary": "No structured training required. Gentle movement is optional.", "instructions": ["Optional easy walk.", "Light stretching if it feels good.", "Hydrate, eat normally, and prioritize sleep.", "Review the first week without judging it."]},
{"day": 8, "week": 2, "type": "Strength circuit", "name": "Lower Body Progression", "minutes": 30, "image": "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=1200&q=85", "summary": "Progress by adding a little resistance or 2\u20133 reps where form stays clean.", "instructions": ["Circuit A: goblet squat 12, reverse lunge 12/side, hip thrust 15, calf raise 22.", "Circuit B: step-up 12/side, Romanian deadlift 12, split squat 8/side, wall sit 40 sec.", "Repeat both circuits once."]},
{"day": 9, "week": 2, "type": "Intervals + core", "name": "Cardio Intervals & Core", "minutes": 38, "image": "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=85", "summary": "Intervals should feel challenging but controlled, not maximal.", "instructions": ["5-minute easy warm-up.", "8 rounds: 1 minute brisk/hard + 2 minutes easy.", "Core: dead bug 12/side, bird dog 12/side, side plank 30 sec/side for 2 rounds.", "Cool down 5 minutes."]},
{"day": 10, "week": 2, "type": "Strength circuit", "name": "Upper Body Progression", "minutes": 30, "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=85", "summary": "Use slightly more resistance than Week 1 if technique is solid.", "instructions": ["Circuit A: incline or floor push-up 10\u201312, row 14, shoulder tap 12/side, dead bug 12/side.", "Circuit B: overhead press 12, rear-delt row 12, plank 40 sec, side plank 25\u201330 sec/side.", "Repeat both circuits once."]},
{"day": 11, "week": 2, "type": "Recovery", "name": "Mobility & Easy Walk", "minutes": 25, "image": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=85", "summary": "Recovery day: low effort, slow breathing and comfortable range of motion.", "instructions": ["15-minute easy walk.", "Hip flexor stretch 60 sec/side.", "90/90 switches 10/side.", "Thoracic rotation 10/side.", "Hamstring stretch 45 sec/side.", "2\u20133 minutes slow breathing."]},
{"day": 12, "week": 2, "type": "Conditioning", "name": "Full Body Progression", "minutes": 30, "image": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=85", "summary": "Keep the session smooth and repeatable. Avoid grinding reps.", "instructions": ["Circuit A: squat to press 14, reverse lunge + knee 10/side, plank step-out 12/side, deadlift 14.", "Circuit B: step-up 12/side, push-up 10\u201312, mountain climber 14/side, bridge march 14/side.", "Repeat both circuits once."]},
{"day": 13, "week": 2, "type": "Cardio", "name": "Long Easy Cardio", "minutes": 45, "image": "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?auto=format&fit=crop&w=1200&q=85", "summary": "Build aerobic volume at an easy-to-moderate effort.", "instructions": ["5-minute easy warm-up.", "35 minutes steady cardio at RPE 5\u20136.", "5-minute cool-down.", "Optional gentle stretching."]},
{"day": 14, "week": 2, "type": "Rest", "name": "Rest & Repeat", "minutes": 15, "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=85", "summary": "Finish the cycle with recovery, then repeat from Day 1 when ready.", "instructions": ["Optional relaxed walk.", "Review which exercises felt easiest and hardest.", "If recovery is good, repeat the 14-day cycle.", "If unusually sore or fatigued, take another easy day before restarting."]},
];

